server:
  port: 19091

spring:
  application:
    name: gateway
  config:
    import: optional:file:.env[.properties]

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
    
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
              
          routes:
            - id: order-command
              uri: lb://${ORDER_SERVICE_ID}
              predicates:
                - Path=/api/v1/orders/**
                - Method=POST,PUT,PATCH,DELETE
              filters:
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@userKeyResolver}"
                    redis-rate-limiter.replenishRate: 2
                    redis-rate-limiter.burstCapacity: 4
                    redis-rate-limiter.requestedTokens: 1
                
            - id: order-query
              uri: lb://${ORDER_SERVICE_ID}
              predicates:
                - Path=/api/v1/orders/**
                - Method=GET
            
            - id: auth
              uri: lb://${AUTH_SERVICE_ID}
              predicates:
                - Path=/api/v1/users/**
            
            - id: inventory
              uri: lb://${INVENTORY_SERVICE_ID}
              predicates:
                - Path=/api/v1/inventories/**
                
            - id: payment
              uri: lb://${PAYMENT_SERVICE_ID}
              predicates:
                - Path=/api/v1/payments/**
                
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    instance-id: ${spring.application.name}:${server.port}
      
app:
  auth:
    gateway-secret: ${GATEWAY_SECRET}
          